# Generated by Django 4.2.5 on 2023-09-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
